"""
Original source: https://weautomate.org/articles/using-vite-js-with-django/
"""
 
# PROJECT_ROOT/theme/templatetags/vite.py

from os import path
import re
import json

from django import template
from django.conf import settings
from django.utils.safestring import mark_safe
from django.templatetags.static import static
from django.contrib.staticfiles.finders import find

register = template.Library()

is_absolute_url = lambda url: re.match("^https?://", url)

# DEV = settings.DEBUG
# DEV_SERVER_ROOT = "http://localhost:3001"

manifest_filepath = path.join(path.abspath(path.dirname(__file__)), '../static/frontend/manifest.json') 

# @register.simple_tag
# def render_vite_bundle():
#     """
#     Template tag to render a vite bundle.
#     Supposed to only be used in production.
#     For development, see other files.
#     """

#     try:
#         fd = open(manifest_filepath, "r")
#         manifest = json.load(fd)
#     except:
#         raise Exception(
#             f"Vite manifest file not found or invalid. Maybe your {settings.VITE_APP_DIR}/dist/manifest.json file is empty?"
#         )

#     imports_files = "".join(
#         [
#             f'<script type="module" src="/static/{manifest[file]["file"]}"></script>'
#             for file in manifest["index.html"]["imports"]
#         ]
#     )

#     return mark_safe(
#         f"""<script type="module" src="/static/{manifest['index.html']['file']}"></script>
#         <link rel="stylesheet" type="text/css" href="/static/{manifest['index.html']['css'][0]}" />
#         {imports_files}"""
#     )


def vite_manifest(entries_names):


    # manifest_filepath = static('frontend/manifest.json')


    # if DEV:
    #     scripts = [
    #         f"{DEV_SERVER_ROOT}/@vite/client",
    #     ]

    #     for name in entries_names:
    #         scripts.append(f'{DEV_SERVER_ROOT}/{name}')

    #     styles = []
    #     return scripts, styles

    with open(manifest_filepath) as fp:
        manifest = json.load(fp)
    _processed = set()

    def _process_entries(names):
        scripts = []
        styles = []

        for name in names:
            if name in _processed:
                continue

            chunk = manifest[name]

            import_scripts, import_styles = _process_entries(chunk.get('imports', []))
            scripts += import_scripts
            styles += import_styles

            scripts += [chunk['file']]
            styles += [css for css in chunk.get('css', [])]

            _processed.add(name)

        return scripts, styles

    return _process_entries(entries_names)


@register.simple_tag(name="vite_styles")
def vite_styles(*entries_names):
    """
    Populate an html template with styles generated by vite

    Usage::

        {% vite_styles 'main.js' 'other-entry.js' %}

    Examples::
        <head>
            ...
            {% vite_styles 'main.js' 'other-entry.js' %}
        </head>
    """
    _, styles = vite_manifest(entries_names)
    # styles = map(lambda href: href if is_absolute_url(href) else static(href), styles)
    styles = map(lambda src: "/static/frontend/" + src, styles)
    as_link_tag = lambda href: f'<link rel="stylesheet" href="{href}" />'
    return mark_safe("\n".join(map(as_link_tag, styles)))


@register.simple_tag(name="vite_scripts")
def vite_scripts(*entries_names):
    """
    Populate an html template with script tags generated by vite

    Usage::

        {% vite_scripts 'main.js' 'other-entry.js' %}

    Examples::
        <body>
            <!-- Your HTML -->
            {% vite_scripts 'main.js' 'other-entry.js' %}
        </body>
    """
    scripts, _ = vite_manifest(entries_names)
    # scripts = map(lambda src: src if is_absolute_url(src) else static(src), scripts)
    scripts = map(lambda src: "/static/frontend/" + src, scripts)
    as_script_tag = lambda src: f'<script type="module" src="{src}"></script>'
    return mark_safe("\n".join(map(as_script_tag, scripts)))