/**
 * Autogenerated by https://github.com/originjs/webpack-to-vite
 */

import { defineConfig } from 'vite';
import path from 'path';
import vue from '@vitejs/plugin-vue2'
// import { createVuePlugin } from 'vite-plugin-vue2'; // REPLACED BY: @vitejs/plugin-vue2
import envCompatible from 'vite-plugin-env-compatible';
// import { createHtmlPlugin } from 'vite-plugin-html';
import { viteCommonjs } from '@originjs/vite-plugin-commonjs';
// import djangoVite from 'django-vite-plugin'

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: [
      { find: /^~/, replacement: '' },
      { find: '@', replacement: path.resolve(__dirname, 'src') }
    ],
    extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json', '.vue' ]
  },
  plugins: [
    vue(),
    // createVuePlugin({ jsx: true }),
    // djangoVite(['frondend/main.js',]),
    viteCommonjs(),
    envCompatible(),
    // createHtmlPlugin({
    //   inject: {
    //     data: {
    //       title: 'g3w-portal'
    //     }
    //   }
    // })
  ],
  base: (process.env === 'production' ? '/static/frontend/' : './'),
  server: {
    strictPort: false,
    port: 8080,
    origin: 'http://localhost:8080',
  },
  build: {
    emptyOutDir: true,
    manifest: true,
    outDir: '../static/frontend/',
    // assetsDir: 'assets',
    rollupOptions: {
      // input: [
      //   './src/main.ts'
      // ],
      output: {
        entryFileNames: `[name].js`,
        chunkFileNames: `portal-[name].js`,
        assetFileNames: `assets/[name].[ext]`
      },
    },
    sourcemap: true,
  }
})
